language: java
install: true
addons:
  sonarcloud:
    organization: bosofelipe-github
    token:
      secure: 11f824a47e91797b8b394444d725aae5cd339bf7
os: linux
dist: trusty
jdk:
  - openjdk11

script:
  - gradle build --scan -s
  - gradle sonarqube