language: java
install: true
addons:
  sonarcloud:
    organization: bosofelipe-github
    token:
      secure: 9fa95782aea30931b84cd302b7bafa9331a810d0

os: linux
dist: trusty
jdk: oraclejdk11

script:
  - gradle build --scan -s
  - gradle sonarqube